### PR TITLE
Abigail's Week 6 Survey

### PR DESCRIPTION
**Pull request by abigailorbe**
Hi!

I added some background information in the markdown file so hopefully that adds some context in terms of the purpose of the survey and what advice I'm hoping you can give. Thanks!

Abigail

### CODE REVIEW

**Comment by MarineAntonio** [comment]
Hi Abby, you’ve designed a really great survey! I will list my comments below, but all in all, it seems well designed. You paid really strong attention to details, like asking “what was the first state” and then doing a repeat group asking “what was the next state.” Great job.

**Comment by MarineAntonio** [comment]
For the demographics question about age, one comment I have is that answering “1985” or “1995” shouldn’t end the survey since you could be born in those years and be 37 or 27, which fits your sample population of interest.
Perhaps you should design this question so that you get a specific age rather than respondents’ birth years, like we did in class.
I also wonder if a message explaning why some birth years are disqualifying would be helpful. I actually don’t know if there is a way around it, but it was jarring to say “2001” and have the survey end with no explanation. (This is a low priority change. if possible at all!)

**Comment by MarineAntonio** [comment]
Something that was tedious was that, after responding that I attended school in multiple states, the survey asked me to specifically answer “In which state did you complete _?” for every grade. I prefer the format of checking off which grades I attended school in the states I listed. It is easier to check boxes than scroll through states, and it is more concise dealing with fewer pages (assuming that someone went to school in less than 13 states). I would go with the checkboxes option, i.e., asking which grades of school people attended by state!

**Review by MarineAntonio — CHANGES_REQUESTED** [review]
See my comments in the Conversation tab!

**Comment by abigailorbe** [comment]
Hi @MarineAntonio,

Thank you for your insightful comments. I made all the updates you mentioned, including removing the grade-by-grade school attendance questions, adding notes about why a participant would be ineligible, and reworking the birth year question to be a question about graduation year. Let me know if there's anything else you'd like me to revise before I merge!

Abigail

**Comment by abigailorbe** [comment]
Hi @MarineAntonio,

I'd like to merge these changes before I start on this week's assignment, so please let me know if you would like any further changes or if the merge is ready to be approved.

Thanks,
Abigail

**Comment by MarineAntonio** [comment]
H @abigailorbe,

It looks great. Good luck with this week's assignment.

Best,
Antonio

**Review by MarineAntonio — APPROVED** [review]

**Pull request merged**
