### PR TITLE
Victoria week6 assignment submission

### PR DESCRIPTION
**Pull request by bp557**

### CODE REVIEW

**Review by AaronShtilerman — COMMENTED** [review]
Hi Victoria! I can't access your google sheets. Is it open to me?

**Comment by bp557** [comment]
> Hi Victoria! I can't access your google sheets. Is it open to me?

Hi Aaron, my apologies for the inconvenience, I just opened the access, and it should be fine this time.

**Comment by AaronShtilerman** [comment]
Good work! I left my comments on the google sheets.

**Comment by bp557** [comment]
> Good work! I left my comments on the google sheets.

Hi Aaron, I have made some changes based on your comments, and I have posted the link of my revised version in my original .md file, pls feel free to review it, thanks!

**Review by AaronShtilerman — APPROVED** [review]
There should be something in the repeat count  column of your repeat group, but aside from that ,you made great revisions!

**Pull request merged**
