### PR TITLE
Week 4 Stata do file

### PR DESCRIPTION
**Pull request by yashdhuldhoya**

### CODE REVIEW

**Comment by yashdhuldhoya** [comment]
Hey Abigail! A couple of points: 

1. For question 2, I created my loop, but I'm unable to view my temp file so I am not sure if the loop was successful or not. I Would appreciate comments there. 
2. For question 3, I relied very heavily on your do-file. Though, I made sure to understand every step of the process. Thanks for a super neat and elegant solution. 

The other three questions took me quite a while, and I had to get to other things so I did not get to think as deeply about the third question. But I hope to spend some time on it later tomorrow morning. 

I would appreciate your comments and feedback on my do-file. Thanks a lot, and have a great week ahead!!

**Comment by yashdhuldhoya** [comment]
Hey Abigail! A couple of points:

1. I have resolved the coding error in question 2. You should be able to run the code smoothly. 
2. I have tried to rework the code in question 3 while still arriving at the same result. 

Looking forward to your thoughts. Have a nice evening.

**Review by abigailorbe — COMMENTED** [review]
Hi @yashdhuldhoya,
Here are my notes:

Question 1.
The instructions for part (b) don't ask for a list of villages for which mode_pixel == 1, so I wouldn't include that, as it just muddles up the results window

Question 2.
I am getting an error message when running line 112:
. use `week_4', clear
invalid file specification
r(198);
I'm not sure if this is because I didn't correctly change my working directories, but please double check that this line runs on your device.

Question 3.
As you probably saw in my do-file, I dropped the table21 variable at the end because it's no longer informative once all the columns have been aligned (it's "18 and above" for every row). You can keep it in if you'd like, but I wanted to flag this.

Question 4.
This looks good!

These changes are minimal, so if you'd like to submit it as is, let me know, and I can approve the pull-request.

**Comment by yashdhuldhoya** [comment]
Hi Abigail, 

Thank you so much for your notes, they were all helpful!

I have made the relevant changes to Q1 and Q3. I re-ran the code for Q2 so I'm not sure where the hang-up is. But I'll check with our instructors and get back to you on this one! 

Thank you!

**Review by abigailorbe — APPROVED** [review]

**Pull request merged**
