### PR TITLE
Sylvia

### PR DESCRIPTION
**Pull request by sbrown5x**

### CODE REVIEW

**Comment by sbrown5x** [comment]
Hi Victoria! If you could propose an edit to my files, that would be great! Thank you!

**Comment by BeaLeydier** [comment]
FYI Sylvia, I've just updated the base of your merge to be the develop branch, so you are merging into the develop branch instead of the main one. The aim of this structure is to keep the main branch clean and only do large merges into it, once all smaller edits/merges have been done. But it doesn't change anything to the rest :)

**Comment by sbrown5x** [comment]
Got it, thanks Bea! I think GitKraken only gave me the option to merge into
origin; is there an option I should be selecting in GitHub to make sure I'm
merging into the develop branch?

Thanks,
Sylvia

**Review by bp557 — CHANGES_REQUESTED** [review]
Hi Sylvia, please add the name of your favorite drink to your bio file. Thx!

**Comment by sbrown5x** [comment]
Hi all, I'm having some trouble because of conflicting files in .DS_Store and Bios/.DS_Store that I'm having trouble resolving. I'm going to create a new branch called sylvia2 with the changes you requested, Victoria, and will ask for your review on that. Sorry for the confusion!

**Comment by BeaLeydier** [comment]
Got it, thanks to you both! I will close this PR and delete the branch as Sylvia was able to merge her changes with the new branch. And we'll add a gitignore to the repo moving forward to avoid the conflict with this annoying Mac file a lot of you guys ran into.

**Pull request closed without merging**
