### PR TITLE
Bt week2 assignment

### PR DESCRIPTION
**Pull request by Benjamin-Tu**

### CODE REVIEW

**Review by AaronShtilerman — COMMENTED** [review]
Did you edit your files? I'm having difficulty seeing the edits.

**Comment by Benjamin-Tu** [comment]
@AaronShtilerman Hi Aaron, I have just pushed the files. You can see the edit now. Thank you for taking the time to review!

**Review by AaronShtilerman — CHANGES_REQUESTED** [review]
Thanks for pushing. Can you add a comment on your favorite food in your bio file?

**Comment by Benjamin-Tu** [comment]
Hi, I have made the changes.

**Review by AaronShtilerman — APPROVED** [review]
Approved!

**Pull request merged**
