### PR TITLE
Uploading week 6 assignment

### PR DESCRIPTION
**Pull request by shailyacharya**
I'm having a bit of trouble with loading the external csv— any feedback on that or other parts of the survey would be greatly appreciated!

### CODE REVIEW

**Comment by sbrown5x** [comment]
Thanks, Shaily! I'll take a look by tomorrow night :)

**Review by sbrown5x — CHANGES_REQUESTED** [review]
Hi Shaily, great job! My general comments are below, labeled according to which variable I'm referring to.

1. `country_pullcsv`: I see where you had trouble with the external data. In your `search` function, I think instead of `Continent_Code`, you want to put `Continent_Name`, because we select a full continent name in `continent_pullcsv`, not an abbreviation for the continent. (Unfortunately, because the answer options did not load correctly, I was unable to select an option, and because the question was required, I was unable to click through the rest of the survey. However, if you're able to make changes, I'm happy to review again, just let me know! Or alternatively, you could just not make that question required until you manage to fix it.)
2. `name`: I wonder if there’s a way to guarantee that I enter both my first and last name, maybe using regular expressions (`regex()`)? Or you can separate first and last name into separate questions!
3. `gender`, `race`: Is there a way to hyperlink the links you've included in the hints? I think hyperlinks would be more user-friendly. I also wonder whether this information is necessary to include in the survey. Also for these questions, I wonder if you want to ask the people who select `other` to specify in a separate question what they self-identify as (race/gender). You can look at my survey to see how I do this, if that's helpful!
4. `continent_pullcsv`: Is there a way to make the continents alphabetical in continent_pullcsv? Might make it easier/faster for the respondent to choose the right one.
5. `coreopinion`: I was unable to test this in the survey itself, but looking at your Google Sheet, I wonder if this could have had more items on the Likert scale (e.g., five ) to capture more variation in attitudes towards the core curriculum (instead of just sorting people into positive, negative, and neutral).
6. Overall: I’m not an undergraduate student so I wasn't sure how to answer the survey. It might be helpful to mention in the .md file in GitHub that the survey population is undergraduates at Georgetown University, so that I know to pretend to be a Georgetown undergrad when answering.

Let me know if you have any questions!

**Comment by shailyacharya** [comment]
@sbrown5x just updated the survey with your feedback, let me know how it looks!

**Review by sbrown5x — COMMENTED** [review]
Great job, Shaily! I have a few more comments in case you want to or have time to make additional changes. In case you do not, I'll just approve the merge now so that you can merge whenever you're ready.

1. `age`: It let me put my age as 290. I wonder if you'd want to set a min and max possible age in the constraints.
2. `core`: I could select both “None of the Above” and other course options. I would set a constraint such that if they select "None of the above", that is the only one they pick. I think I managed to achieve this in my survey by typing the following in the constraint column: “if(selected(., ***), count-selected(.) = 1, count-selected(.) >= 1)”, where *** is the value you gave the “None of the above” option (in my survey, it was -9).
3. `coursecode`: typo in the hint ("capitalzation")
4. Your repeat group: Because I selected “None of the Above”, this loop asked me about my “None of the Above” class. You may want to set the repeat such that it does not ask questions about this answer option (i.e., does not ask respondents who select this answer option the questions in the repeat group).
5. `creditaccuracy`: Small typo in your scale: “less” should be “fewer” since we’re talking about things that can be counted (credits) rather than something unitless (e.g., time, effort). Also, I think this should be a single choice question rather than a multiple choice question; I can’t have both be pursuing more credits and less (fewer) credits than the amount you include in the question text.
6. `opinion`: i'm not sure the scale is symmetrical (is 'enjoy' the opposite of "dislike"? Shouldn't it be like/dislike?).

**Review by sbrown5x — APPROVED** [review]

**Pull request closed without merging**
